// 2D Raytracing Rendering for Matter.js
// VERHILLE Arnaud
// Copyleft GPL2

const CONFIG = Object.freeze({
    CANVAS_WIDTH: 800,
    CANVAS_HEIGHT: 600,
    RAY_ANGLE_STEP: 0.6,
    BALL_SEGMENTS: 30,
    SPAWN_INTERVAL: 80,
    SPAWN_PROBABILITY: 0.5,
    LIGHT_SPAWN_PROBABILITY: 0.85,
    BALL_SPEED_MAX: 10,
    BALL_SPEED_MIN: 3,
    OFF_SCREEN_MARGIN: 100,
    BALL_RESTITUTION: 0.8,
    VELOCITY_DAMPING: 0.9,
    VELOCITY_BOOST: 1.2,
    BREAKOUT_BALL_VELOCITY: 3,
    BREAKOUT_BALL_RADIUS: 8,
    GRID_CELL_SIZE: 80,
    SHOW_FPS: true,
});
