// 2D Raytracing Rendering for Matter.js
// VERHILLE Arnaud
// Copyleft GPL2

const CONFIG = Object.freeze({
    CANVAS_WIDTH: 800,
    CANVAS_HEIGHT: 600,
    RAY_ANGLE_STEP: 0.6,
    BALL_SEGMENTS: 30,
    SPAWN_INTERVAL: 80,
    SPAWN_PROBABILITY: 0.5,
    LIGHT_SPAWN_PROBABILITY: 0.85,
    BALL_SPEED_MAX: 10,
    BALL_SPEED_MIN: 3,
    OFF_SCREEN_MARGIN: 100,
    BALL_RESTITUTION: 0.8,
    VELOCITY_DAMPING: 0.9,
    VELOCITY_BOOST: 1.2,
    BREAKOUT_BALL_VELOCITY: 3,
    BREAKOUT_BALL_RADIUS: 8,
    GRID_CELL_SIZE: 80,
    SHOW_FPS: true,

    // Glass refraction
    GLASS_REFRACTIVE_INDEX_R: 1.45,
    GLASS_REFRACTIVE_INDEX_G: 1.52,
    GLASS_REFRACTIVE_INDEX_B: 1.62,
    GLASS_SPAWN_PROBABILITY: 0.15,
    MAX_REFRACTION_DEPTH: 3,
    REFRACTED_BEAM_INTENSITY_BOOST: 1.0,
    GLASS_ALPHA: 60,
    GLASS_STROKE_ALPHA: 120,
    REFRACTED_RAY_MAX_LENGTH: 1500,
    BOUNDARY_RAY_MIN_GAP: 2.0,
});
